### ISSUE TITLE
'Cube' object has no attribute 'create_date_hierarchy'

### ISSUE THREAD

**Issue by eric-kaufmann** [atoti/atoti#455]
I tried the following from your [documentation](https://docs.atoti.io/latest/lib/atoti.cube.html#atoti.cube.Cube.create_date_hierarchy)

```
from datetime import date
df = pd.DataFrame(
    columns=["Date", "Quantity"],
    data=[
        (date(2020, 1, 10), 150.0),
        (date(2020, 1, 20), 240.0),
        (date(2019, 3, 17), 270.0),
        (date(2019, 12, 12), 200.0),
    ],
)
table = session.read_pandas(
    df, keys=["Date"], table_name="create_date_hierarchy example"
)
cube = session.create_cube(table)
l, m = cube.levels, cube.measures
cube.create_date_hierarchy("Date parts", column=table["Date"])
cube.query(
    m["Quantity.SUM"],
    include_totals=True,
    levels=[l["Year"], l["Month"], l["Day"]],
)
```

This is the result:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
C:\Users\ERICKA~1\AppData\Local\Temp/ipykernel_6516/4121939050.py in <module>
     14 cube = session.create_cube(table)
     15 l, m = cube.levels, cube.measures
---> 16 cube.create_date_hierarchy("Date parts", column=table["Date"])
     17 cube.query(
     18     m["Quantity.SUM"],

AttributeError: 'Cube' object has no attribute 'create_date_hierarchy'
```

Working on atoti 0.6.3 and Python 3.9.7 (conda 4.11.0)

**Comment by tibdex** [comment]
Hi Eric, you need to upgrade to [atoti 0.6.4](https://docs.atoti.io/0.6.4/releases/0.6.4.html#changed).

**Comment by eric-kaufmann** [comment]
Works perfectly fine! Thanks!
